[package]
name = "nonk-dot-dev"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = { version = "1.0.0", features = ["color"] }
eyre = "0.6.8"
log = { version = "0.4.20", features = ["std"] }
seed = { version = "0.10.0", features = ["routing"] }
