name: Publish to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: ["publish"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  SANITY_URL: https://github.com/nonk123/sanity/releases/download/gh-actions/sanity-release-linux

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Download sanity
        run: wget -O sanity $SANITY_URL && chmod +x sanity
      - name: Render
        run: env RUST_LOG=debug ./sanity
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with: { path: "dist" }
      - name: Publish to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
