name: Deploy to GitHub Pages

on:
  push:
    branches: ["deploy"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: deploy
          lfs: true
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build
        run: |
          wget -O sanity https://github.com/nonk123/sanity/releases/download/gh-actions/sanity-release-linux
          chmod +x sanity
          RUST_LOG=debug ./sanity
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "out"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
